### PR TITLE
upgrade services for helm 3

### PR DESCRIPTION
**Pull request by AyadiAmen**
upgrade the services to fix this https://github.com/cetic/fadi/issues/84

#### Which issue this PR fixes
fix for https://github.com/cetic/fadi/issues/84

update services to work with helm3

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by AyadiAmen** [comment]
ci/circleci: build — Your tests failed on CircleCI failed because when this PR was created Tsaas wasn't updated to V0.1.3 yet.

**Comment by alexnuttinck** [comment]
@AyadiAmen it should be available now.

**Comment by alexnuttinck** [comment]
Thanks for the modifications, @AyadiAmen! By the way, I think it's the good moment to deprecate pgadmin. Could you remove pgadmin from the values.yaml / README.md / requirements.yaml and set adminer to `true` by default? 

(@fzalila ; @banzo for your information)

**Comment by alexnuttinck** [comment]
See issue https://github.com/cetic/fadi/issues/92

**Comment by AyadiAmen** [comment]
@alexnuttinck yes sure

**Review by alexnuttinck — APPROVED** [review]
perfect!

**Comment by AyadiAmen** [comment]
@alexnuttinck thanks !

**Pull request merged**
