### PR TITLE
Update FADI to use the new helm repos instead of the archived repos ( stable & incubator )

### LINKED ISSUE #31: Node-Red disabled
Node-Red Helm chart depends on https://github.com/k8s-at-home/charts/tree/master/charts/common , it is disabled until we can have a better look at it.

### PR DESCRIPTION
**Pull request by AyadiAmen**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  
The helm repos stable and incubator are no longer supported which affects most of the helm charts used on FADI, This PR updates the repos with the new ones alongside using the new version of the NiFi helm chart ( ldap support ), the new version of the Postgres helm chart ( cronjob pull policy ) and adding Drupal.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

### CODE REVIEW

**Comment by banzo** [comment]
@AyadiAmen please provide a more informative title for the PR and a more detailed description.

**Comment by AyadiAmen** [comment]
@banzo thank you for your review, the title and description are changed .

**Comment by alexnuttinck** [comment]
the CI shows that there is a bug with node-red. It should be fixed before we can merge.

**Comment by banzo** [comment]
The CI complains about something in the publish gist: 

```
...
remote: Compressing objects: 100% (292/292), done.        
remote: Total 900 (delta 193), reused 187 (delta 44), pack-reused 562        
Receiving objects: 100% (900/900), 12.37 MiB | 78.18 MiB/s, done.
Resolving deltas: 100% (514/514), done.
>> Add helm repos...
Error: looks like "https://kubernetes-charts-incubator.storage.googleapis.com" is not a valid chart repository or cannot be reached: failed to fetch https://kubernetes-charts-incubator.storage.googleapis.com/index.yaml : 403 Forbidden
...
```

@alexnuttinck what do you think about putting that file in https://github.com/cetic/helm-charts instead of a gist?

**Comment by alexnuttinck** [comment]
@banzo It is due to the deprecation of the stable and incubator helm charts repos. I will fix the script. Ok I can move the script in a repo.I found that using Gist was approriate for a single Bash script used for multiple projets.

**Review by alexnuttinck — APPROVED** [review]
Seems time to merge this PR.

**Pull request merged**
